version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@kever/logger"
    versions:
    - 0.7.10
    - 0.7.8
    - 0.8.0
  - dependency-name: "@kever/core"
    versions:
    - 0.7.12
    - 0.7.13
    - 0.7.14
    - 0.7.15
    - 0.7.8
    - 0.8.0
  - dependency-name: "@kever/router"
    versions:
    - 0.7.10
    - 0.7.8
    - 0.8.0
  - dependency-name: "@kever/ioc"
    versions:
    - 0.7.12
    - 0.7.14
    - 0.7.8
    - 0.8.0
